// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_repository_test.go -package=core Repository
//

// Package core is a generated GoMock package.
package core

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ExecShell mocks base method.
func (m *MockRepository) ExecShell(ctx context.Context, containerID string, stdin io.Reader, stdout, stderr io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecShell", ctx, containerID, stdin, stdout, stderr)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecShell indicates an expected call of ExecShell.
func (mr *MockRepositoryMockRecorder) ExecShell(ctx, containerID, stdin, stdout, stderr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecShell", reflect.TypeOf((*MockRepository)(nil).ExecShell), ctx, containerID, stdin, stdout, stderr)
}

// InspectContainer mocks base method.
func (m *MockRepository) InspectContainer(ctx context.Context, containerID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectContainer", ctx, containerID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectContainer indicates an expected call of InspectContainer.
func (mr *MockRepositoryMockRecorder) InspectContainer(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectContainer", reflect.TypeOf((*MockRepository)(nil).InspectContainer), ctx, containerID)
}

// InspectImage mocks base method.
func (m *MockRepository) InspectImage(ctx context.Context, imageRef string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectImage", ctx, imageRef)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectImage indicates an expected call of InspectImage.
func (mr *MockRepositoryMockRecorder) InspectImage(ctx, imageRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectImage", reflect.TypeOf((*MockRepository)(nil).InspectImage), ctx, imageRef)
}

// InspectNetwork mocks base method.
func (m *MockRepository) InspectNetwork(ctx context.Context, networkID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectNetwork", ctx, networkID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectNetwork indicates an expected call of InspectNetwork.
func (mr *MockRepositoryMockRecorder) InspectNetwork(ctx, networkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectNetwork", reflect.TypeOf((*MockRepository)(nil).InspectNetwork), ctx, networkID)
}

// InspectVolume mocks base method.
func (m *MockRepository) InspectVolume(ctx context.Context, volumeName string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectVolume", ctx, volumeName)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectVolume indicates an expected call of InspectVolume.
func (mr *MockRepositoryMockRecorder) InspectVolume(ctx, volumeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectVolume", reflect.TypeOf((*MockRepository)(nil).InspectVolume), ctx, volumeName)
}

// LoadContainerLogs mocks base method.
func (m *MockRepository) LoadContainerLogs(ctx context.Context, containerID string, tail int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadContainerLogs", ctx, containerID, tail)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadContainerLogs indicates an expected call of LoadContainerLogs.
func (mr *MockRepositoryMockRecorder) LoadContainerLogs(ctx, containerID, tail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadContainerLogs", reflect.TypeOf((*MockRepository)(nil).LoadContainerLogs), ctx, containerID, tail)
}

// LoadContainerMetrics mocks base method.
func (m *MockRepository) LoadContainerMetrics(ctx context.Context, rows []ContainerRow) (map[string]ContainerMetrics, float64, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadContainerMetrics", ctx, rows)
	ret0, _ := ret[0].(map[string]ContainerMetrics)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(uint64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// LoadContainerMetrics indicates an expected call of LoadContainerMetrics.
func (mr *MockRepositoryMockRecorder) LoadContainerMetrics(ctx, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadContainerMetrics", reflect.TypeOf((*MockRepository)(nil).LoadContainerMetrics), ctx, rows)
}

// LoadContainerRows mocks base method.
func (m *MockRepository) LoadContainerRows(ctx context.Context) ([]ContainerRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadContainerRows", ctx)
	ret0, _ := ret[0].([]ContainerRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadContainerRows indicates an expected call of LoadContainerRows.
func (mr *MockRepositoryMockRecorder) LoadContainerRows(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadContainerRows", reflect.TypeOf((*MockRepository)(nil).LoadContainerRows), ctx)
}

// LoadSupportingResources mocks base method.
func (m *MockRepository) LoadSupportingResources(ctx context.Context) (Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSupportingResources", ctx)
	ret0, _ := ret[0].(Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSupportingResources indicates an expected call of LoadSupportingResources.
func (mr *MockRepositoryMockRecorder) LoadSupportingResources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSupportingResources", reflect.TypeOf((*MockRepository)(nil).LoadSupportingResources), ctx)
}
