// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_repository_test.go -package=core Repository,ContainerLister,MetricsProvider,LogsProvider,Inspector,ShellProvider
//

// Package core is a generated GoMock package.
package core

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockContainerLister is a mock of ContainerLister interface.
type MockContainerLister struct {
	ctrl     *gomock.Controller
	recorder *MockContainerListerMockRecorder
	isgomock struct{}
}

// MockContainerListerMockRecorder is the mock recorder for MockContainerLister.
type MockContainerListerMockRecorder struct {
	mock *MockContainerLister
}

// NewMockContainerLister creates a new mock instance.
func NewMockContainerLister(ctrl *gomock.Controller) *MockContainerLister {
	mock := &MockContainerLister{ctrl: ctrl}
	mock.recorder = &MockContainerListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerLister) EXPECT() *MockContainerListerMockRecorder {
	return m.recorder
}

// LoadContainerRows mocks base method.
func (m *MockContainerLister) LoadContainerRows(ctx context.Context) ([]ContainerRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadContainerRows", ctx)
	ret0, _ := ret[0].([]ContainerRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadContainerRows indicates an expected call of LoadContainerRows.
func (mr *MockContainerListerMockRecorder) LoadContainerRows(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadContainerRows", reflect.TypeOf((*MockContainerLister)(nil).LoadContainerRows), ctx)
}

// LoadSupportingResources mocks base method.
func (m *MockContainerLister) LoadSupportingResources(ctx context.Context) (Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSupportingResources", ctx)
	ret0, _ := ret[0].(Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSupportingResources indicates an expected call of LoadSupportingResources.
func (mr *MockContainerListerMockRecorder) LoadSupportingResources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSupportingResources", reflect.TypeOf((*MockContainerLister)(nil).LoadSupportingResources), ctx)
}

// MockMetricsProvider is a mock of MetricsProvider interface.
type MockMetricsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsProviderMockRecorder
	isgomock struct{}
}

// MockMetricsProviderMockRecorder is the mock recorder for MockMetricsProvider.
type MockMetricsProviderMockRecorder struct {
	mock *MockMetricsProvider
}

// NewMockMetricsProvider creates a new mock instance.
func NewMockMetricsProvider(ctrl *gomock.Controller) *MockMetricsProvider {
	mock := &MockMetricsProvider{ctrl: ctrl}
	mock.recorder = &MockMetricsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsProvider) EXPECT() *MockMetricsProviderMockRecorder {
	return m.recorder
}

// LoadContainerMetrics mocks base method.
func (m *MockMetricsProvider) LoadContainerMetrics(ctx context.Context, rows []ContainerRow) (map[string]ContainerMetrics, float64, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadContainerMetrics", ctx, rows)
	ret0, _ := ret[0].(map[string]ContainerMetrics)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(uint64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// LoadContainerMetrics indicates an expected call of LoadContainerMetrics.
func (mr *MockMetricsProviderMockRecorder) LoadContainerMetrics(ctx, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadContainerMetrics", reflect.TypeOf((*MockMetricsProvider)(nil).LoadContainerMetrics), ctx, rows)
}

// MockLogsProvider is a mock of LogsProvider interface.
type MockLogsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockLogsProviderMockRecorder
	isgomock struct{}
}

// MockLogsProviderMockRecorder is the mock recorder for MockLogsProvider.
type MockLogsProviderMockRecorder struct {
	mock *MockLogsProvider
}

// NewMockLogsProvider creates a new mock instance.
func NewMockLogsProvider(ctrl *gomock.Controller) *MockLogsProvider {
	mock := &MockLogsProvider{ctrl: ctrl}
	mock.recorder = &MockLogsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogsProvider) EXPECT() *MockLogsProviderMockRecorder {
	return m.recorder
}

// LoadContainerLogs mocks base method.
func (m *MockLogsProvider) LoadContainerLogs(ctx context.Context, containerID string, tail int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadContainerLogs", ctx, containerID, tail)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadContainerLogs indicates an expected call of LoadContainerLogs.
func (mr *MockLogsProviderMockRecorder) LoadContainerLogs(ctx, containerID, tail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadContainerLogs", reflect.TypeOf((*MockLogsProvider)(nil).LoadContainerLogs), ctx, containerID, tail)
}

// MockInspector is a mock of Inspector interface.
type MockInspector struct {
	ctrl     *gomock.Controller
	recorder *MockInspectorMockRecorder
	isgomock struct{}
}

// MockInspectorMockRecorder is the mock recorder for MockInspector.
type MockInspectorMockRecorder struct {
	mock *MockInspector
}

// NewMockInspector creates a new mock instance.
func NewMockInspector(ctrl *gomock.Controller) *MockInspector {
	mock := &MockInspector{ctrl: ctrl}
	mock.recorder = &MockInspectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInspector) EXPECT() *MockInspectorMockRecorder {
	return m.recorder
}

// InspectResource mocks base method.
func (m *MockInspector) InspectResource(ctx context.Context, resourceType ResourceType, id string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectResource", ctx, resourceType, id)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectResource indicates an expected call of InspectResource.
func (mr *MockInspectorMockRecorder) InspectResource(ctx, resourceType, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectResource", reflect.TypeOf((*MockInspector)(nil).InspectResource), ctx, resourceType, id)
}

// MockShellProvider is a mock of ShellProvider interface.
type MockShellProvider struct {
	ctrl     *gomock.Controller
	recorder *MockShellProviderMockRecorder
	isgomock struct{}
}

// MockShellProviderMockRecorder is the mock recorder for MockShellProvider.
type MockShellProviderMockRecorder struct {
	mock *MockShellProvider
}

// NewMockShellProvider creates a new mock instance.
func NewMockShellProvider(ctrl *gomock.Controller) *MockShellProvider {
	mock := &MockShellProvider{ctrl: ctrl}
	mock.recorder = &MockShellProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShellProvider) EXPECT() *MockShellProviderMockRecorder {
	return m.recorder
}

// ExecShell mocks base method.
func (m *MockShellProvider) ExecShell(ctx context.Context, containerID string, stdin io.Reader, stdout, stderr io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecShell", ctx, containerID, stdin, stdout, stderr)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecShell indicates an expected call of ExecShell.
func (mr *MockShellProviderMockRecorder) ExecShell(ctx, containerID, stdin, stdout, stderr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecShell", reflect.TypeOf((*MockShellProvider)(nil).ExecShell), ctx, containerID, stdin, stdout, stderr)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ExecShell mocks base method.
func (m *MockRepository) ExecShell(ctx context.Context, containerID string, stdin io.Reader, stdout, stderr io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecShell", ctx, containerID, stdin, stdout, stderr)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecShell indicates an expected call of ExecShell.
func (mr *MockRepositoryMockRecorder) ExecShell(ctx, containerID, stdin, stdout, stderr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecShell", reflect.TypeOf((*MockRepository)(nil).ExecShell), ctx, containerID, stdin, stdout, stderr)
}

// InspectResource mocks base method.
func (m *MockRepository) InspectResource(ctx context.Context, resourceType ResourceType, id string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectResource", ctx, resourceType, id)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectResource indicates an expected call of InspectResource.
func (mr *MockRepositoryMockRecorder) InspectResource(ctx, resourceType, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectResource", reflect.TypeOf((*MockRepository)(nil).InspectResource), ctx, resourceType, id)
}

// LoadContainerLogs mocks base method.
func (m *MockRepository) LoadContainerLogs(ctx context.Context, containerID string, tail int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadContainerLogs", ctx, containerID, tail)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadContainerLogs indicates an expected call of LoadContainerLogs.
func (mr *MockRepositoryMockRecorder) LoadContainerLogs(ctx, containerID, tail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadContainerLogs", reflect.TypeOf((*MockRepository)(nil).LoadContainerLogs), ctx, containerID, tail)
}

// LoadContainerMetrics mocks base method.
func (m *MockRepository) LoadContainerMetrics(ctx context.Context, rows []ContainerRow) (map[string]ContainerMetrics, float64, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadContainerMetrics", ctx, rows)
	ret0, _ := ret[0].(map[string]ContainerMetrics)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(uint64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// LoadContainerMetrics indicates an expected call of LoadContainerMetrics.
func (mr *MockRepositoryMockRecorder) LoadContainerMetrics(ctx, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadContainerMetrics", reflect.TypeOf((*MockRepository)(nil).LoadContainerMetrics), ctx, rows)
}

// LoadContainerRows mocks base method.
func (m *MockRepository) LoadContainerRows(ctx context.Context) ([]ContainerRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadContainerRows", ctx)
	ret0, _ := ret[0].([]ContainerRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadContainerRows indicates an expected call of LoadContainerRows.
func (mr *MockRepositoryMockRecorder) LoadContainerRows(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadContainerRows", reflect.TypeOf((*MockRepository)(nil).LoadContainerRows), ctx)
}

// LoadSupportingResources mocks base method.
func (m *MockRepository) LoadSupportingResources(ctx context.Context) (Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSupportingResources", ctx)
	ret0, _ := ret[0].(Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSupportingResources indicates an expected call of LoadSupportingResources.
func (mr *MockRepositoryMockRecorder) LoadSupportingResources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSupportingResources", reflect.TypeOf((*MockRepository)(nil).LoadSupportingResources), ctx)
}

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// ExecShell mocks base method.
func (m *MockServiceInterface) ExecShell(ctx context.Context, containerID string, stdin io.Reader, stdout, stderr io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecShell", ctx, containerID, stdin, stdout, stderr)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecShell indicates an expected call of ExecShell.
func (mr *MockServiceInterfaceMockRecorder) ExecShell(ctx, containerID, stdin, stdout, stderr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecShell", reflect.TypeOf((*MockServiceInterface)(nil).ExecShell), ctx, containerID, stdin, stdout, stderr)
}

// InspectResource mocks base method.
func (m *MockServiceInterface) InspectResource(ctx context.Context, resourceType ResourceType, id string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectResource", ctx, resourceType, id)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectResource indicates an expected call of InspectResource.
func (mr *MockServiceInterfaceMockRecorder) InspectResource(ctx, resourceType, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectResource", reflect.TypeOf((*MockServiceInterface)(nil).InspectResource), ctx, resourceType, id)
}

// LoadContainerLogs mocks base method.
func (m *MockServiceInterface) LoadContainerLogs(ctx context.Context, containerID string, tail int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadContainerLogs", ctx, containerID, tail)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadContainerLogs indicates an expected call of LoadContainerLogs.
func (mr *MockServiceInterfaceMockRecorder) LoadContainerLogs(ctx, containerID, tail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadContainerLogs", reflect.TypeOf((*MockServiceInterface)(nil).LoadContainerLogs), ctx, containerID, tail)
}

// LoadContainerMetrics mocks base method.
func (m *MockServiceInterface) LoadContainerMetrics(ctx context.Context, rows []ContainerRow) (map[string]ContainerMetrics, float64, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadContainerMetrics", ctx, rows)
	ret0, _ := ret[0].(map[string]ContainerMetrics)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(uint64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// LoadContainerMetrics indicates an expected call of LoadContainerMetrics.
func (mr *MockServiceInterfaceMockRecorder) LoadContainerMetrics(ctx, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadContainerMetrics", reflect.TypeOf((*MockServiceInterface)(nil).LoadContainerMetrics), ctx, rows)
}

// LoadContainerRows mocks base method.
func (m *MockServiceInterface) LoadContainerRows(ctx context.Context) ([]ContainerRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadContainerRows", ctx)
	ret0, _ := ret[0].([]ContainerRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadContainerRows indicates an expected call of LoadContainerRows.
func (mr *MockServiceInterfaceMockRecorder) LoadContainerRows(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadContainerRows", reflect.TypeOf((*MockServiceInterface)(nil).LoadContainerRows), ctx)
}

// LoadSnapshot mocks base method.
func (m *MockServiceInterface) LoadSnapshot(ctx context.Context) (Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSnapshot", ctx)
	ret0, _ := ret[0].(Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSnapshot indicates an expected call of LoadSnapshot.
func (mr *MockServiceInterfaceMockRecorder) LoadSnapshot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSnapshot", reflect.TypeOf((*MockServiceInterface)(nil).LoadSnapshot), ctx)
}

// LoadSupportingResources mocks base method.
func (m *MockServiceInterface) LoadSupportingResources(ctx context.Context) (Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSupportingResources", ctx)
	ret0, _ := ret[0].(Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSupportingResources indicates an expected call of LoadSupportingResources.
func (mr *MockServiceInterfaceMockRecorder) LoadSupportingResources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSupportingResources", reflect.TypeOf((*MockServiceInterface)(nil).LoadSupportingResources), ctx)
}
